### ISSUE TITLE
Usage of your tool

### ISSUE THREAD

**Issue by judiciousmind** [bakshi-gulam/veth-change-speed#1]
Dear Bakshi,
May i know how to use your code to create virtual interfaces with custom speed. Appreciate your early reply.
best regards

**Comment by bakshi-gulam** [comment]
You need to find veth.c for your linux kernel. Just merge these changes to your kernel version and give make. Then install veth.ko using insmod command. After this you should be able to change the virtual interface speed using ethtool.

Marking this as "Not an Issue."
